trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Build
    jobs:
    - job: Firstjob
      steps:
      - bash: echo build Firstjob
    - job: secondjob
      steps:
      - bash: echo build secondjob
      
    
  - stage: DevDeploy
    dependsOn: Build
    jobs:
    - job: Firstjob
      steps:
      - bash: echo DevDeploy Firstjob
    - job: secondjob
      steps:
      - bash: echo DevDeploy secondjob

  - stage: QADeploy
    dependsOn: Build
    jobs:
    - job: Firstjob
      steps:
      - bash: echo  QADeploy Firstjob
    - job: secondjob
      steps:
      - bash: echo  QADeploy secondjob
      
  - stage: ProDeploy
    dependsOn:
     - Build
     - DevDeploy
     - QADeploy
    jobs:
    - job: Firstjob
      steps:
      - bash: echo ProDeploy Firstjob
    - job: secondjob
      steps:
      - bash: echo ProDeploy secondjob
  



