trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Build
    jobs:
    - job: Firstjob
      steps: 
      - bash: echo $(Build.ArtifactStagingDirectory) 
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.BuildId) 
      - bash: echo $(Build.BuildNumber) 
      - bash: echo $(Build.Repository.Name) 
      - bash: echo $(Build.SourceBranch) 
      - bash: echo $(Build.SourceBranch) 
      - bash: echo $(Build.ArtifactStagingDirectory) 
      - bash: ls -R $(Build.ArtifactStagingDirectory) 

# clcik on show assistant to add new task and search copy file from one dir to another dir
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            **/*.yaml
            **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'





 
      
    
  # - stage: DevDeploy
  #   variables:
  #    environment: Dev
  #   dependsOn: Build
  #   jobs:
  #   - job: Firstjob
  #     steps:
  #     - bash: echo $(environment) Firstjob
  #   - job: secondjob
  #     steps:
  #     - bash: echo $(environment) secondjob

  # - stage: QADeploy
  #   variables:
  #    environment: QA
  #   dependsOn: Build
  #   jobs:
  #   - job: Firstjob
  #     steps:
  #     - bash: echo   $(environment) Firstjob
  #   - job: secondjob
  #     steps:
  #     - bash: echo  $(environment) secondjob
      
  # - stage: ProdDeploy
  #   variables:
  #    environment: Prod
  #   dependsOn:
  #    - Build
  #    - DevDeploy
  #    - QADeploy
  #   jobs:
  #   - job: Firstjob
  #     steps:
  #     - bash: echo $(environment) Firstjob
  #   - job: secondjob
  #     steps:
  #     - bash: echo $(environment) secondjob
  



