
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#  before clicking here setting for modification
# - task: Docker@2
#       displayName: Build an image
#       inputs:
#         command: build
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         tags: |
#           $(tag)
#  after  clicking here setting for modification
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'sankar1999-docker-hub'
        repository: 'sankar1999/currency-exchange-d'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
